services:
  frontend:
    container_name: edutie-frontend
    image: edutie/frontend-app
    build: 
      context: ./edutie-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./edutie-frontend/node_modules:/app/node_modules
      - ./edutie-frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontendnetwork

networks:
  frontendnetwork:
    name: frontendnetwork