services:
  frontend:
    build: 
      context: ./edutie-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./edutie-frontend/nginx.conf:/etc/nginx/nginx.conf