services:
  frontend:
    container_name: edutie-frontend
    image: edutie/frontend-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./node_modules:/app/node_modules
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontendnetwork

networks:
  frontendnetwork:
    name: frontendnetwork