name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./edutie-frontend
        run: npm install

      - name: Build
        working-directory: ./edutie-frontend
        run: npm run build
  
      - name: Test
        working-directory: ./edutie-frontend
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Deploy
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./edutie-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/edutie-frontend:${{ github.sha }}
          build-args: |
            APP_VERSION=${{ github.sha }}