name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./edutie-frontend
        run: npm install

      - name: Build
        working-directory: ./edutie-frontend
        run: npm run build
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Build and Deploy
        uses: docker/build-push-action@v5
        with:
          context: ./edutie-frontend
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/edutie-frontend:${{ github.sha }}
          build-args: |
            APP_VERSION=${{ github.sha }}