name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest' # You can specify a version here

      - name: Install dependencies with Bun
        working-directory: ./edutie-frontend
        run: bun install

      - name: Build with Vite
        working-directory: ./edutie-frontend
        run: bunx --bun vite build

      - name: Test with Bun
        working-directory: ./edutie-frontend
        run: bun test

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./edutie-frontend
          file: ./edutie-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/edutie-frontend:latest